[platformio]
default_envs = esp32devkitv1_uart_bridge
src_dir = tools/esp32_wifi_uart_bridge

[env:esp32devkitv1_uart_bridge]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
board_build.f_cpu = 240000000L
; Override these for private deployments, for example:
; build_flags =
;   -D NUEDC_AP_SSID=\"NUEDC-CAR-UART\"
;   -D NUEDC_AP_PASS=\"your-password\"

